### ISSUE TITLE
jep.PyJList to Python list

### ISSUE THREAD

**Issue by Vkynluv** [mrj0/jep#72] opened 2017-04-05 05:34 UTC
I am using JEPP - java embedded python, I am trying to send a arraylist from java to python. while receiving the arraylist in python its type is jep.PyJList. now i have to cast that type(jep.PyJList) to normal python list.

**Comment by bsteffensmeier** [comment] 2017-04-05 21:19
PyJList was designed to support the concept of duck typing, wherever possible it supports all the operations that you can do on a normal python list. For most use cases there is no good reason to convert it to a normal python list, just use the PyJList as though it were a list.

If there is some reason that the duck typing is not good enough and you really do need a normal python list you can just use the list constructor method to create a new list just as you would with any other python sequence type. The following shows an example of converting an ArrayList to a list using the jep interactive console:

```python
>>> from java.util import ArrayList
>>> a = ArrayList()
>>> type(a)
<type 'jep.PyJList'>
>>> b = list(a)
>>> type(b)
<type 'list'>
```

**Comment by bsteffensmeier** [comment] 2017-04-06 18:40
Since this answer was accepted on [stackoverflow](http://stackoverflow.com/questions/43222386/jepp-java-embedded-python-jep-pyjlist-to-python-list) I am going to assume that it resolved your problems close this issue.

**Closed by bsteffensmeier** 2017-04-06 18:40 UTC
