### ISSUE TITLE
Jep throwing exception on import cvxpy after close 

### ISSUE THREAD

**Issue by behdad84** [mrj0/jep#31] opened 2015-10-19 04:14 UTC
Hi,

I am seeing "'NoneType' object has no attribute" error when running the following code:

    val j1 = new Jep()
    j.eval("import cvxpy")
    j.close()
    val j2 = new Jep()
    j2.eval("import cvxpy")

Interestingly something related to close() method is causing the problem. The code works for other libraries such as numpy.

So the following is fine:
    val j = new Jep()
    j.eval("import numpy;")
    j.close()
    val j2 = new Jep()
    j2.eval("import numpy;")

Even more interestingly if I create multiple Jep instances on different threads in same JVM it works. So each thread can import cvxpy and start working. Super interestingly if two jep object are created on different threads such that one threads starts working and finishes its work and calls the close() method when the next thread starts and creates its own Jep isnatce and tries to do "import cvxpy" the problem again occurs.

Please let me know if I am doing something wrong here. 

Thank you.  

that is causing the error. In the following situations I don't see the error.

**Comment by ndjensen** [comment] 2015-10-19 13:01
Can you paste the stacktrace of the error?  I'm guessing it goes into cvxpy a bit before throwing the error.

**Comment by behdad84** [comment] 2015-10-19 22:03
Please see the following. Thank you. 


Exception in thread "main" jep.JepException: jep.JepException: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'logical_or'
at jep.Jep.eval(Jep.java:471)
at com.verizon.bda.util.PythonScriptRunner$.main(PythonScriptRunner.scala:113)
at com.verizon.bda.util.PythonScriptRunner.main(PythonScriptRunner.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: jep.JepException: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'logical_or'
at /Users/me/Library/Python/2.7/lib/python/site-packages/numpy/core/_methods._any(_methods.py:32)
at /Users/me/Library/Python/2.7/lib/python/site-packages/numpy/core/fromnumeric.any(fromnumeric.py:1838)
at /Users/me/Library/Python/2.7/lib/python/site-packages/numpy/core/machar._do_init(machar.py:127)
at /Users/me/Library/Python/2.7/lib/python/site-packages/numpy/core/machar.__init__(machar.py:111)
at /Users/me/Library/Python/2.7/lib/python/site-packages/numpy/core/getlimits._init(getlimits.py:151)
at /Users/me/Library/Python/2.7/lib/python/site-packages/numpy/core/getlimits.__new__(getlimits.py:121)
at /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/linalg/decomp_schur.<module>(decomp_schur.py:152)
at /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/linalg/__init__.<module>(__init__.py:180)
at /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/special/orthogonal.<module>(orthogonal.py:101)
at /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/special/basic.<module>(basic.py:18)
at /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/special/__init__.<module>(__init__.py:603)
at /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cvxpy/atoms/kl_div.<module>(kl_div.py:25)
at /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cvxpy/atoms/__init__.<module>(__init__.py:22)
at /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cvxpy/__init__.<module>(__init__.py:21)

**Comment by ndjensen** [comment] 2015-10-19 23:30
This is roughly the same as #28 where the method logical_or is lost after the first interpreter is disposed.  We haven't yet been able to track this down deep enough to understand if this is a problem with numpy, jep, or python itself.  It's not cvxpy though and it should be easily repeatable just by trying to import some of the specific methods from numpy, closing the interpreter, then repeating the import.

For the short term you probably have to not dispose of the Jep instances, instead retaining them, possibly in a thread pool.  In the long term we need to figure out if Jep can somehow handle this better to avoid the problem or if we need to submit a bug to numpy or python.  This is complex stuff, if you can track deeper what is going on and why the reference is lost and not reused or reinitialized, that would help.

**Comment by behdad84** [comment] 2015-10-20 00:35
One way to get around this is delaying the "import cvxpy" until the function call which actually uses the library. So I moved the "import cvxpy" to the function body rather than the script global space and it actually works.

**Comment by bsteffensmeier** [comment] 2015-10-20 06:31
I've traced it through the cpython and numpy code and I think I understand the problem.

When the jep interpreter is closed we call [Py_EndInterpreter](https://github.com/mrj0/jep/blob/master/src/jep/pyembed.c#L340) which calls [Py_ImportCleanup](https://github.com/python/cpython/blob/1fe0fd9feb6a4472a9a1b186502eb9c0b2366326/Python/pylifecycle.c#L828) calling [_PyModule_Clear](https://github.com/python/cpython/blob/1fe0fd9feb6a4472a9a1b186502eb9c0b2366326/Python/import.c#L460) which finally [ends up setting all the module items to None.](https://github.com/python/cpython/blob/1fe0fd9feb6a4472a9a1b186502eb9c0b2366326/Objects/moduleobject.c#L594)

The root of the problem is in the numpy c code where it [imports the _mehods module into c](https://github.com/numpy/numpy/blob/c3b48b91f151be1bd0f94cb0f05ad2e400dee9b4/numpy/core/src/multiarray/methods.c#L57) and [save methods to a static variables.](https://github.com/numpy/numpy/blob/c3b48b91f151be1bd0f94cb0f05ad2e400dee9b4/numpy/core/src/multiarray/methods.c#L113) Since the [variable um is part of the module](https://github.com/numpy/numpy/blob/v1.8.2/numpy/core/_methods.py#L11), it is set to None as part of _PyModule_Clear. The 'any' function itself is still held in the static variable but when the function is called it [looks up the value for the variable 'um'](https://github.com/numpy/numpy/blob/v1.8.2/numpy/core/_methods.py#L32) which is None which has no logical_or attribute causing the exception.

This is not something we can fix in jep since the problem is in a static variable created by numpy. A naive solution would be modify _methods.py and  move the import of the umath module into the any method so that it did not need to reference any variables defined in the module. However in newer versions of numpy they did the exact opposite, [moving the logical_or.reduce into a variable](https://github.com/numpy/numpy/blob/c3b48b91f151be1bd0f94cb0f05ad2e400dee9b4/numpy/core/_methods.py#L20). It seems this was a performance enhancement so if we undid that and moved the import within the method it would slow things down slightly. There is probably some other way to access or cache that method but I'm not familiar enough with numpy source to recommend a solution and any further discussion should probably head over to the numpy page to get input from the devs there.

**Comment by behdad84** [comment] 2015-10-20 08:54
FYI I only see the problem for cvxpy. numpy actually works fine. So the following works fine:

    val j = new Jep()
    j.eval("import numpy")
    j.close()
    val j2 = new Jep()
    j2.eval("import numpy")
    j2.close()

**Comment by bsteffensmeier** [comment] 2015-10-20 14:50
Importing numpy doesn't cache the method, they aren't cached until they are executed. The simplest test cast that isolates the problem to numpy would be:

```java
Jep jep = new Jep();
jep.eval("import numpy");
jep.eval("numpy.ndarray([1]).any()");
jep.close();
jep = new Jep();
jep.eval("import numpy");
jep.eval("numpy.ndarray([1]).any()");
jep.close();
```

**Comment by ndjensen** [comment] 2015-10-21 16:18
Ben, can you copy your analysis above where you traced the root of the problem and paste it onto #28?  Then I can close this one as a duplicate.

**Closed** 2015-10-22 17:47 UTC
Labels: duplicate
